import streamlit as st


st.title("What is this project about?")

text = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at placerat sem, vitae lobortis lectus. Suspendisse venenatis mattis facilisis. Phasellus massa diam, condimentum et augue non, pharetra laoreet tellus. Quisque luctus rhoncus lacus, nec aliquam erat ornare ut. Aliquam sit amet accumsan lacus. Aenean dignissim dui massa, non faucibus felis varius id. Integer in dolor dapibus, faucibus risus vel, facilisis erat. Donec quam lorem, hendrerit eget nunc eget, dictum tempus turpis. Proin luctus vestibulum sem. Pellentesque id dui eget justo molestie iaculis. Phasellus viverra at ex ac efficitur.\n
Aenean placerat luctus aliquam. Phasellus pulvinar augue et gravida auctor. Cras nisi diam, consequat ac dui in, scelerisque malesuada lectus. Donec ultrices augue lorem, nec dapibus nunc porta id. Fusce imperdiet, velit sed tempor fringilla, est eros lobortis orci, in bibendum nunc sem non ex. Donec vestibulum, velit vel ultricies imperdiet, nunc dolor convallis ipsum, et consequat nisi felis vel dui. Praesent vitae ex nec neque cursus pellentesque quis quis sem. Nullam maximus dui quis augue mattis gravida. Morbi elementum urna mi, eu sollicitudin quam ultrices in.\n
Phasellus ullamcorper mi ipsum, at consectetur est dapibus non. Morbi quis gravida risus. Vestibulum ut consequat sem, in efficitur justo. Integer ac semper diam. Fusce sollicitudin orci nec efficitur tempor. Etiam quis ante feugiat, elementum est euismod, pretium lacus. Duis pulvinar purus quis condimentum dapibus. Nullam accumsan sapien lectus, nec sodales tellus ornare et. Aliquam erat volutpat. Pellentesque laoreet metus id mattis euismod. Aenean aliquet, nulla non viverra rutrum, orci magna fringilla magna, in egestas nisl est a erat. Donec eu urna at nulla rutrum rutrum. Etiam at efficitur metus. Mauris lacinia sem sit amet ultrices volutpat. Maecenas sollicitudin maximus tortor, vel eleifend nulla accumsan eget. Proin vitae velit nisi.\n
"""
st.markdown(text)